---
title: "Evaluating approaches to backcalculating cases counts by date of infection from cases counts by date of report"
output: github_document
---

**Authors:** EpiForecasts, CMMID Covid working group, Sebastian Funk


## Summary

## Introduction

## Methods

* Orginal implementation here: https://github.com/jhellewell14/rtconfirm/blob/master/R/backcalc.R

* Packages

```{r}
library(EpiNow)
library(data.table)
```

* Simulate data

```{r}
## Define an initial rt vector 
rts <- c(rep(2, 20), (2 - 1:15 * 0.1), rep(0.5, 10))
rts

## Use the mean default generation interval for covid
generation_interval <- rowMeans(EpiNow::covid_generation_times)

## Sample a report delay as a lognormal
delay_def <- EpiNow::lognorm_dist_def(mean = 5, mean_sd = 1,
                                      sd = 3, sd_sd = 1, max_value = 30,
                                       samples = 1)


## Sample a incubation period (again using the default for covid)
incubation_def <- EpiNow::lognorm_dist_def(mean = EpiNow::covid_incubation_period[1, ]$mean,
                                          mean_sd = EpiNow::covid_incubation_period[1, ]$mean_sd,
                                          sd = EpiNow::covid_incubation_period[1, ]$sd,
                                          sd_sd = EpiNow::covid_incubation_period[1, ]$sd_sd,
                                          max_value = 30, samples = 1)

## Simulate cases with a decrease in reporting at weekends and an incease on Monday                                     
simulated_cases <- simulate_cases(rts, initial_cases = 100 , initial_date = as.Date("2020-03-01"),
                    generation_interval = generation_interval, delay_def = delay_def,
                   incubation_def = incubation_def, reporting_effect = c(1.1, rep(1, 4), 0.95, 0.95))

simmulated_cases
```
    
    
* Fit model and compare to simulated data and ability to recover reporting effects.

* Fit to observed data: Austria (see `backcalc.R`) example.

## Results

## Discussion

## References
